### ISSUE TITLE
Support to package or compile as an executable app

### ISSUE THREAD

**Issue by liudonghua123** [aalykiot/dune#6]
Wow, this is a tiny js/ts runtime, it's so cute and fantastic. If it support to package or compile as an executable app, that's would be perfect.

Some workarounds of node: pkg, nexe. See the implementation of deno also. ☺

**Comment by aalykiot** [comment]
@liudonghua123 Nice idea! Currently, I'm trying to complete the target-api and implement some more important stuff but it's not an impossible feature to implement in the future. By looking a bit at Deno (compile) the `dune bundle` will be a prerequisite.

**Comment by aalykiot** [comment]
@liudonghua123 compile as a standalone executable is now available in [v0.2.1](https://github.com/aalykiot/dune/releases/tag/v0.2.1) 🎉

**Comment by aalykiot** [comment]
Thanks for the feedback.

The problems you're facing while compiling with dune base binary not located in `$HOME/.dune/bin` and with the command line arguments being parsed by dune (while running a standalone) will be fixed (on v0.2.2) when I merge this #9 PR.

Also, I added a compression step when compiling standalone programs using the [zstd](https://github.com/facebook/zstd) algorithm that will reduce their size to some extent.

> Dead code elimination is already happing in `dune bundle` or `dune compile` since it's a default feature of SWC.

@liudonghua123 tell me what you think and, thanks for your feedback/suggestions that help me make dune a better runtime 🙂
