### ISSUE TITLE
How would you go about building a JavaScript runtime to do one thing: Local HTTPS server

### ISSUE THREAD

**Issue by guest271314** [aalykiot/dune#85]
Ideally something like this https://github.com/guest271314/native-messaging-deno/blob/local-server-dynamic/local_server.js, and that's it. The idea is to use the least amount of resources to build, omitting baking liniting, testing, formatting ,docs, and all other unrequired components from the source and build.

How would you go about achieving that goal?

**Comment by guest271314** [comment]
A standalone JavaScript runtime that implemented _only_ a WebSocket server would also suffice for local HTTPS server. That's it. A cursory roadmap for how you would achieve that would be helpful.

**Comment by aalykiot** [comment]
Hello @guest271314 👋

Well I'm not that much familiar with OpenSSL, TSL, etc. Having said that I would probably choose to add TLS support in the event-loop directly (using [rustls](https://github.com/rustls/rustls/)) so we can have TLC sockets available in the Rust side.

Examples:
- https://github.com/rustls/rustls/blob/main/examples/src/bin/tlsclient-mio.rs
- https://github.com/rustls/rustls/blob/main/examples/src/bin/tlsserver-mio.rs

That will make the JavaScript bit simpler IMO cause the JavaScript code will just read/write from/to a socket (just like what I'm trying to do currently with plain [HTTP support for dune](https://github.com/aalykiot/dune/blob/http-module/src/js/http.js)) and all the encryption/decryption will happen in Rust.

Now I might be wrong here but, I think this might be a good approach considering the current event-loop structure in Dune.

> P.S. If you have any more feedback or suggestions on how I can improve Dune please don't hesitate to share 🙂

**Comment by guest271314** [comment]
> That will make the JavaScript bit simpler IMO cause the JavaScript code will just read/write from/to a socket (just like what I'm trying to do currently with plain [HTTP support for dune](https://github.com/aalykiot/dune/blob/http-module/src/js/http.js)) and all the encryption/decryption will happen in Rust.

Is that HTTP commit on the main branch? How can I test? 

I observed that Deno HTTPS server when serving a constant local stream increases CPU usage to 85%+ and I can hear the machine spinning trying to keep up https://gist.github.com/guest271314/a8eace7cb17019a8833a28c297759072.

**Comment by aalykiot** [comment]
> Is that HTTP commit on the main branch? How can I test?

@guest271314 At the moment, the HTTP module is on the `http-module` branch as I'm running some additional tests on it. To test this module, you'll need to clone the repository, switch to the http-module branch, and compile Dune from source.

> I observed that Deno HTTPS server...

At this point, I have only implemented an HTTP client (the server will come later), so I'm not sure it will be useful for your benchmarks. As a single person working on this project, I can only do so much, and these things can be quite complex, as I'm sure you understand... 🤷‍♂️

**Comment by guest271314** [comment]
Thanks. I havn't yet been ablt to compile a Rust source code because of the 1GB+ necessary to even set up Rust. I'll close this and visit back again when you have HTTP server working.
