### ISSUE TITLE
Add compatibility for running the typescript compiler (tsc)

### ISSUE THREAD

**Issue by Slipyx** [aalykiot/dune#89]
Would be nice for dune to be able to run the typescript compiler, and with that, the possibility of 'dune compile' to make a standalone typescript compiler executable.

**Comment by aalykiot** [comment]
Hmmm @Slipyx that is an interesting idea that I didn't thought before. I'll take a closer look to that. 👍

**Comment by aalykiot** [comment]
@Slipyx I know it's been over a year 😅, but I think it's possible to do what you recommended.

```js
import tsc from 'https://esm.sh/typescript@5.4.5';
 
const code = 'function foo(a: number, b: number) { return a + b; }';
const result = tsc.transpile(code);
 
console.log(result);
```

In theory you can build a CLI interface given this document: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API and build a binary executable using `dune compile`.
